// AUTO-GENERATED by scripts/fetch-icarus.mjs — do not edit by hand.
// Source: Steam achievement schema for Icarus (appid 1149460).
// Re-run `node scripts/fetch-icarus.mjs` to refresh.
import type { IcarusAchievement } from '@/types/icarus'

export const icarusAchievements: IcarusAchievement[] = [
  {
    "id": "kill-sandworm-boss",
    "steamApiName": "ACH_KILL_SANDWORM_BOSS",
    "name": "The Bigger They Are…",
    "description": "Kill the Sandworm Boss on the Hardest Difficulty",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/db669c393d7e2b86d1d387e4842ca2cbbf539299.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e38aed7ee8c2bc22468b8e5f7625ae51698517e9.jpg"
  },
  {
    "id": "kill-landshark-boss",
    "steamApiName": "ACH_KILL_LANDSHARK_BOSS",
    "name": "… The Harder They Fall",
    "description": "Kill the Landshark Boss on the Hardest Difficulty",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/585d909057ce6ba3079f82c73857df8c33f43f65.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/98c20d10a3271fb66f54097259f00088cdbf8d85.jpg"
  },
  {
    "id": "kill-scorpion-boss",
    "steamApiName": "ACH_KILL_SCORPION_BOSS",
    "name": "Sting Operation",
    "description": "Kill the Scorpion Boss on the Hardest Difficulty",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/4223f224e3c99b3c5a4add589d9dd527346e1ff6.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/4f9b746864d34abf0a2738e39b7dc5865faea8bd.jpg"
  },
  {
    "id": "kill-wolf-boss",
    "steamApiName": "ACH_KILL_WOLF_BOSS",
    "name": "Leader Of The Pack",
    "description": "Kill the Alpha Wolf Boss on the Hardest Difficulty",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/2b31bda73fcbdff9d64b2d381f3bbd55f3411c86.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/b2db738e77b8c9714d4d9de0416ca1c663af8705.jpg"
  },
  {
    "id": "complete-styx",
    "steamApiName": "ACH_COMPLETE_STYX",
    "name": "Styx And Stones",
    "description": "Complete every Styx Mission",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/a5dea003ad9ac61fc2de522fa3c16ef518f86ca1.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/2a8d355123764c435b3a4408af573aa152895c55.jpg"
  },
  {
    "id": "complete-olympus",
    "steamApiName": "ACH_COMPLETE_OLYMPUS",
    "name": "Zero To Hero",
    "description": "Complete every Olympus Mission",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/fd66b4b84d8f552146e8633e209bc86579a6abc4.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/ff2b1e865ba8d965689fb17d3f9cd4330c958677.jpg"
  },
  {
    "id": "credits",
    "steamApiName": "ACH_CREDITS",
    "name": "Money Money Money",
    "description": "Collect 10000 Credits",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/7282d1ccb65c7bfe3530d895eae14e966d320e41.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/f78f6bd02c211c10a88bec2abca1c665db9c07b2.jpg"
  },
  {
    "id": "exotics",
    "steamApiName": "ACH_EXOTICS",
    "name": "Ore-mageddon",
    "description": "Collect 10000 Exotics",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/c6edf7b1fd88c7888f407738a4f8616e014c36c5.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1f91fd2b69f605fcdc2e04a8c6ef3ca7469756d7.jpg"
  },
  {
    "id": "t1-blueprints",
    "steamApiName": "ACH_T1_BLUEPRINTS",
    "name": "Bear Necessities",
    "description": "Unlock all blueprints in T1",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/f0265a4cdf1a001901239b7a8fb95c770feac7f2.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/5319ec370d777514bb56af69ec6608b22447c54c.jpg"
  },
  {
    "id": "t2-blueprints",
    "steamApiName": "ACH_T2_BLUEPRINTS",
    "name": "Unlocked and Loaded",
    "description": "Unlock all blueprints in T2",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/42fe085f07cee3bbc0e2405acb35ce648c5aa593.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/4aa7f56975e7b5c76a432ddfbcab45bc6ad367ef.jpg"
  },
  {
    "id": "t3-blueprints",
    "steamApiName": "ACH_T3_BLUEPRINTS",
    "name": "Unlocking Intensifies",
    "description": "Unlock all blueprints in T3",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/061789cf6fd61c007fd277f029f42fb98d8f8a61.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/caa6ec77321620c9b5d3b8848e5b6cf22310bf28.jpg"
  },
  {
    "id": "t4-blueprints",
    "steamApiName": "ACH_T4_BLUEPRINTS",
    "name": "Bench Enthusiast",
    "description": "Unlock all blueprints in T4",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/f0980ae66a14b6d24fd55d54fd90a5d762dc7116.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/7cf366a467c900883466e94442a5810020315e11.jpg"
  },
  {
    "id": "catch-all-fish",
    "steamApiName": "ACH_CATCH_ALL_FISH",
    "name": "Master Angler",
    "description": "Catch these fish on Olympus and Styx",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/b89984e8d979c57a106d1febc1b309be89137bb5.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/3531511517b83300fe7abe335689700fd9cbe220.jpg"
  },
  {
    "id": "complete-bestiary",
    "steamApiName": "ACH_COMPLETE_BESTIARY",
    "name": "Gotta Catch Them All",
    "description": "Max Rank these creatures in the Bestiary. They are present on Olympus or Styx.",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/a5d02596acc2cb78f55bf93be0878452ec070f6e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/4e9072f75891847fe339725ea7952f6851dc0914.jpg"
  },
  {
    "id": "struck-by-lightning",
    "steamApiName": "ACH_STRUCK_BY_LIGHTNING",
    "name": "At least it never hits the same place twice..",
    "description": "Get struck by lightning",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/f762790fdfbe7871cc933d32ee0cf6f373683df6.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/fdfbe004deaf874661e956d33ead65c6e523ec4a.jpg"
  },
  {
    "id": "struck-by-lightning-again",
    "steamApiName": "ACH_STRUCK_BY_LIGHTNING_AGAIN",
    "name": "Sometimes it does…",
    "description": "Get struck by lighting… again",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/76cfbb48f0877116d8223301fb94f11b0aa367bd.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/460a6fcf25227d5947a8d967d4ce819f6c9e40ca.jpg"
  },
  {
    "id": "grenade-deer",
    "steamApiName": "ACH_GRENADE_DEER",
    "name": "Buck And Cover",
    "description": "Kill a Deer with a grenade",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/5a542f96eb67f3d40cf46aa50d1d8df42991b52f.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/22aa433756814e60ea3effe0c0f8e3378a3acc53.jpg"
  },
  {
    "id": "shoot-fish",
    "steamApiName": "ACH_SHOOT_FISH",
    "name": "Pain In The Bass",
    "description": "Catch a fish with a bow and arrow",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/10c72ebea5fb62d6c14574f524686d8ec7f3c08e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e03e1df784057357e2e484c494a51c135a6268d8.jpg"
  },
  {
    "id": "medic",
    "steamApiName": "ACH_MEDIC",
    "name": "Medic!",
    "description": "Revive a downed prospector",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/3df3801175d7b9d52f0742e1c2efb7bf965296cb.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/08d21b815f114318d3ada42928b8f1e3026dd52f.jpg"
  },
  {
    "id": "kill-zebra",
    "steamApiName": "ACH_KILL_ZEBRA",
    "name": "Pony Slaystation",
    "description": "Kill 250 Zebra",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/cfaac2c6fb043bbc26787a7912fc6e6d50952b00.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/714abf009ab7cc5eb4eeac760e983ee35c9fba73.jpg"
  },
  {
    "id": "burn-shelter",
    "steamApiName": "ACH_BURN_SHELTER",
    "name": "Fired Up",
    "description": "Burn down a shelter",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8622eeb3e8fd67d76d57d2b994e4b84a76a3c77b.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/aa3bdffb7df57b57ff71644e10b6aaad447f8fe7.jpg"
  },
  {
    "id": "grenade-crate",
    "steamApiName": "ACH_GRENADE_CRATE",
    "name": "Ex-Box",
    "description": "Break a crate with a grenade",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/53b383e90eb21a097420629fa3ddac97a58aaed3.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/f89087d8728fbbca8e59aedcf0b0524828059ed7.jpg"
  },
  {
    "id": "friendly-fire",
    "steamApiName": "ACH_FRIENDLY_FIRE",
    "name": "Friendly Fire",
    "description": "Kill another prospector",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/24d2b39f55ae982824afe1216be027917a9bc01c.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/01f1c925334597a4ad0ce8d16afe498a9da8e5f7.jpg"
  },
  {
    "id": "tutorial",
    "steamApiName": "ACH_TUTORIAL",
    "name": "Baby Steps",
    "description": "Complete the tutorial",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/b4e370ed6c81377a40f5816501fca0f0433207ed.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/7c815e60a88602c6ab0dce54d730e637fc6c1b3a.jpg"
  },
  {
    "id": "talent-tree",
    "steamApiName": "ACH_TALENT_TREE",
    "name": "Highly Skilled",
    "description": "Reach the bottom of a talent tree",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/20a6a7501eed457b591a703ec3f5aa0519239a77.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/357cce014981a478eb80eeafb920b9ac86447957.jpg"
  },
  {
    "id": "level-cap",
    "steamApiName": "ACH_LEVEL_CAP",
    "name": "Veteran Prospector",
    "description": "Reach the Level Cap",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/ea55ddeb0c413a74f3ffe007ca5c8970ca7671ba.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d16eced5c4e2a98121127c707d7cd55341ee9b92.jpg"
  },
  {
    "id": "melee-kills",
    "steamApiName": "ACH_MELEE_KILLS",
    "name": "Whack-a-Mole",
    "description": "Get 10,000 Melee Kills",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/02791ceb98e2c3a42218163fad2028e225d66b8e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/462970fc49098ddb8115b2cc422970b1a6b79161.jpg"
  },
  {
    "id": "bow-kills",
    "steamApiName": "ACH_BOW_KILLS",
    "name": "Quiver Me Timbers",
    "description": "Get 10,000 Bow & Arrow Kills",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/99159f46285f2c34b79242b210ea38022551229e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1f9ac7313dbe0d933b2a59ab2600ae5627d2f20c.jpg"
  },
  {
    "id": "gun-kills",
    "steamApiName": "ACH_GUN_KILLS",
    "name": "Lock, Stock and Lots of Bears",
    "description": "Get 10,000 Gun Kills",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8f3370f59d0801fcf1fa91f33bc8c7960fa1e7c5.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/ff92a46fdbab78d0c70a3841ab224658f799a58d.jpg"
  },
  {
    "id": "critical-kills",
    "steamApiName": "ACH_CRITICAL_KILLS",
    "name": "One Shot, One Kill",
    "description": "Get 1000 Stealth Critical hit kills",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/c66840f73e9108e79d42be80574dda52e03e5ddc.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1e90568ab865ec3477ea3f46a42517ef90c0d3de.jpg"
  },
  {
    "id": "collect-plants",
    "steamApiName": "ACH_COLLECT_PLANTS",
    "name": "Herb Your Enthusiasm",
    "description": "Harvest these plants",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e9e6488a0be74019755e2409ab6c34e71c2284a6.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/2155b25fc1ca107c44a2201d1a5f57988ccd3a02.jpg"
  },
  {
    "id": "collect-ore",
    "steamApiName": "ACH_COLLECT_ORE",
    "name": "Rock 'n' Roll",
    "description": "Mine these ores",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/cdc9f490c827fd6d509a9ce7c980073431d63365.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e636abadda50f7f4072694c0bd4adeea927bf1b5.jpg"
  },
  {
    "id": "cook-food",
    "steamApiName": "ACH_COOK_FOOD",
    "name": "Yes Chef!",
    "description": "Cook these food items",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/452c9836a4008ee4b5b6a7a27688774e8f465ca7.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/39473fa25cd9513247b53cf654cbc00c67ed4581.jpg"
  },
  {
    "id": "alter-item",
    "steamApiName": "ACH_ALTER_ITEM",
    "name": "Makeshift Engineering",
    "description": "Alter an item",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1a718c4693115828f005d570c9c6ded690c8fbc7.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/b9271d8f7f32d69b6749291fa90346b59b484bdc.jpg"
  },
  {
    "id": "survive",
    "steamApiName": "ACH_SURVIVE",
    "name": "Survival 101",
    "description": "Pick up a stick, stone, or oxite",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e72a92b3e3ce59af0057cc38066500f6c9b94a7f.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/7dbbc67a024ac19a46326223bf5838a726e25d20.jpg"
  },
  {
    "id": "first-death",
    "steamApiName": "ACH_FIRST_DEATH",
    "name": "Whoops!",
    "description": "First time your prospector dies",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/a89398f643ba08303a5395423963d8d24ef60085.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/05010bd29d9e3a24fd1186915cb52f6a1a8ef166.jpg"
  },
  {
    "id": "explore-biomes",
    "steamApiName": "ACH_EXPLORE_BIOMES",
    "name": "Biome Is Where The Heart Is",
    "description": "Explore these biomes on Olympus & Styx",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/5ae675e9458a2e32af4d739547c57583e78a36d3.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/447257b3a5b221474224e9b1f07313df7077c8be.jpg"
  },
  {
    "id": "thumper",
    "steamApiName": "ACH_THUMPER",
    "name": "Mined Over Matter",
    "description": "Activate the Thumper",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/655d2d7c364667fdb03e0dccd1b78bb7e5861075.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/726020f35f62cdd775ccd5c5c51a597a3aa6b7d8.jpg"
  },
  {
    "id": "wear-armor",
    "steamApiName": "ACH_WEAR_ARMOR",
    "name": "Armored and Dangerous",
    "description": "Equip a full set of armor",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/b5145383d9c66e061c8b4c0c33587a3af572240f.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/97536f6756c9f45a4473fcb56d62f1543d728aea.jpg"
  },
  {
    "id": "killed-by-bear",
    "steamApiName": "ACH_KILLED_BY_BEAR",
    "name": "Welcome to Icarus",
    "description": "First time killed by a bear",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/462ad2410267f735dcb9cf36ba797ebd8bbd4817.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d060bf48176367c18f0c3c0e54028e05fbe9c7bb.jpg"
  },
  {
    "id": "kill-rockgolem-boss",
    "steamApiName": "ACH_KILL_ROCKGOLEM_BOSS",
    "name": "Fault Line",
    "description": "Defeat the Quarrite",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/341c446cdb2e3187b4d4e6f7a671ef8fdac8f12f.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/4075e2f02ac910425c5c00846fd47355669051cd.jpg"
  },
  {
    "id": "kill-icemammoth-boss",
    "steamApiName": "ACH_KILL_ICEMAMMOTH_BOSS",
    "name": "Cold-Blooded",
    "description": "Defeat the Rimetusk",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/2e6291a33fbe73dad80efa1a77a72c184d503537.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/fff155a9e70f6b5e61ce1d86987dbfbba8a73ef2.jpg"
  },
  {
    "id": "kill-ape-boss",
    "steamApiName": "ACH_KILL_APE_BOSS",
    "name": "Gone Bananas",
    "description": "Defeat the Garganutan",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/2322b07922895e87520f27a52c88347bd4a6a87e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1c8e01ba49041bc48d2b3ec0d09511458d6ff05c.jpg"
  },
  {
    "id": "kill-slug-boss",
    "steamApiName": "ACH_KILL_SLUG_BOSS",
    "name": "Ooze Control",
    "description": "Defeat the Hammerhead",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/38e27f2ac54622afcb51c2f9ef5ac5fdb7ad4a6a.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8f705d5cf9e833be8994a7a87c99ff56f07e9d01.jpg"
  },
  {
    "id": "kill-lavahunter-boss",
    "steamApiName": "ACH_KILL_LAVAHUNTER_BOSS",
    "name": "Meltdown",
    "description": "Defeat the Lava Hunter",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/0d39186938a5c69abbb30f9b36e5ed4896c019b9.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/145c18a4567010ef61f9e6ebef9d35a9bec6f3a1.jpg"
  },
  {
    "id": "kill-rockgolem-boss-hard",
    "steamApiName": "ACH_KILL_ROCKGOLEM_BOSS_HARD",
    "name": "Rock and a Hard Place",
    "description": "Defeat the Quarrite on the Hardest difficulty",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/7bdd8dc6e2a2844a0c65f1031a183248596650ed.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/c97e75e95325e381a44002637478207f6aadfceb.jpg"
  },
  {
    "id": "kill-icemammoth-boss-hard",
    "steamApiName": "ACH_KILL_ICEMAMMOTH_BOSS_HARD",
    "name": "Tusks to Dust",
    "description": "Defeat the Rimetusk on the Hardest difficulty",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/3db1570410b782dfc0b5266ec9f9373d71fd46ce.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/2effedfdc1a98dd1670dfced8c5b37662a3232f6.jpg"
  },
  {
    "id": "kill-ape-boss-hard",
    "steamApiName": "ACH_KILL_APE_BOSS_HARD",
    "name": "Ape-x Predator",
    "description": "Defeat the Garganutan on the Hardest difficulty",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/c5e7fa34420946537b725dde1d8456ec2fa0423e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/f01f9892af731206e8625e58140244ee00c689d8.jpg"
  },
  {
    "id": "kill-lavahunter-boss-hard",
    "steamApiName": "ACH_KILL_LAVAHUNTER_BOSS_HARD",
    "name": "Too Hot to Handle",
    "description": "Kill the Lava Hunter on the Hardest difficulty",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/03ecc22090e9e54075f5430d79682a5933069951.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/5fa8d8b6b86b9199add1f346f072c0185ca38a23.jpg"
  },
  {
    "id": "kill-slug-boss-hard",
    "steamApiName": "ACH_KILL_SLUG_BOSS_HARD",
    "name": "Nailed It",
    "description": "Kill the Hammerhead on the Hardest difficulty",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8d3cc293a04589722c6b0968029852fbe8c0f77d.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/35152bace72b350c5c2da61609f9bd3c08f5d435.jpg"
  },
  {
    "id": "complete-rockgolem-campaign",
    "steamApiName": "ACH_COMPLETE_ROCKGOLEM_CAMPAIGN",
    "name": "Hero of the Mines",
    "description": "Complete the Quarrite Campaign",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/c276597158346800b68d6d7a43f336046bdd5333.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/f610a4042a3d9eda6e8daed95c9b5c945f27c8c0.jpg"
  },
  {
    "id": "complete-icemammoth-campaign",
    "steamApiName": "ACH_COMPLETE_ICEMAMMOTH_CAMPAIGN",
    "name": "Nothing to see Here",
    "description": "Complete the Rimetusk Campaign",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/57aa5cc275f2a2e358239fe7d447ca5156ae8c90.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/9e23aa3e48bccc0db2d68f31e416705d1812f69f.jpg"
  },
  {
    "id": "complete-ape-campaign",
    "steamApiName": "ACH_COMPLETE_APE_CAMPAIGN",
    "name": "What Experiment?",
    "description": "Complete the Garganutan Campaign",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/79d5bf421cd8124c9333f8db7a3e260f4e39c65c.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/4f2d03509e53881093f4565f7a2761044ac17cd7.jpg"
  },
  {
    "id": "full-rockgolem-campaign",
    "steamApiName": "ACH_FULL_ROCKGOLEM_CAMPAIGN",
    "name": "Faultless Victory",
    "description": "Fully complete all missions in the Quarrite Campaign - This requires multiple campaign playthroughs",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/0bae88acc3f032113aee7c7f06b968459514aea5.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e7c000431c510f2d9bc28458b8b9f76796fc653a.jpg"
  },
  {
    "id": "full-icemammoth-campaign",
    "steamApiName": "ACH_FULL_ICEMAMMOTH_CAMPAIGN",
    "name": "Glacial Supremacy",
    "description": "Fully complete all missions in the Rimetusk Campaign - This requires multiple campaign playthroughs",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/a86b26e53dcf32bbbf41fd269f4aaf7d07ed2476.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/ae96321727e00b5d1df38e360b26a04514aa2228.jpg"
  },
  {
    "id": "full-ape-campaign",
    "steamApiName": "ACH_FULL_APE_CAMPAIGN",
    "name": "Colossus Collapse",
    "description": "Fully complete all missions in the Garganutan Campaign - This requires multiple campaign playthroughs",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8efb2b1b1a558a59b14cbd5d9bd1147606324a63.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/55dd7c749553b52726d100d69afc57d83e7d46bb.jpg"
  },
  {
    "id": "legendary-weapon",
    "steamApiName": "ACH_LEGENDARY_WEAPON",
    "name": "Matter Reforged",
    "description": "Craft a Legendary Weapon",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/0f99fc5a07beddee4c34a78364621047aab702d4.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/a66a94d073e6651caaa76828c3cf66b8ac66c813.jpg"
  },
  {
    "id": "legendary-weapon-upgrade",
    "steamApiName": "ACH_LEGENDARY_WEAPON_UPGRADE",
    "name": "Weaponized Perfection",
    "description": "Fully Upgrade a Legendary Weapon",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/206dcad102abc9f13b79431ea4b8f4d88729edd9.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/baf3315523f8dfdee89036c5a22680f144aff3dd.jpg"
  },
  {
    "id": "extract-biomass",
    "steamApiName": "ACH_EXTRACT_BIOMASS",
    "name": "Flesh and Circuitry",
    "description": "Extract 1000 Pieces of Biomass",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/6c75b215e10e2c246529c2081e0a4a9e890d6437.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/23dc9bd53bc6cffa749e0f7d26dd8e2ec52740af.jpg"
  },
  {
    "id": "icebreaker",
    "steamApiName": "ACH_ICEBREAKER",
    "name": "What is That?",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/fe6e5e1fbebc904d41274e1b1062b97cc3170149.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/be8bcae1daa5481fb39f17206f80814d1198bf9c.jpg",
    "hidden": true
  },
  {
    "id": "crushed",
    "steamApiName": "ACH_CRUSHED",
    "name": "Press F to Pay Respects",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e0fb256fc1f25173e5200f88e9948ba84de1a4df.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/76ee1b1229825e7f9d67aeae3174e0ac2f1c11e4.jpg",
    "hidden": true
  },
  {
    "id": "nullsec-icesheet-middle",
    "steamApiName": "ACH_NULLSEC_ICESHEET_MIDDLE",
    "name": "Calm Before the Storm",
    "description": "Reach the Middle Ice Sheet in the Null Sector",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/ba1a5b29887d1a5ed716f3d8697115c6520f1034.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/c248d637981dfb3439040a71b37374a84b7e0aea.jpg"
  },
  {
    "id": "nullsec-ashlands",
    "steamApiName": "ACH_NULLSEC_ASHLANDS",
    "name": "Not Lost",
    "description": "Travel Through the Ashlands to the Ice Sheet",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/237d8c5861ec990b8098a9b1c104710dc31c0f04.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/0e1cb32b2ad41ccb24e9156c8bb47f527813e495.jpg"
  },
  {
    "id": "nullsec-icesheet",
    "steamApiName": "ACH_NULLSEC_ICESHEET",
    "name": "Still Not Lost",
    "description": "Discover the Cave Deep Within the Ice Sheet",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/9505bda4dc863911caa96080c8f72839119dbdc6.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/bcedea235631d02da5a73b0ea90c85016a1c1a9a.jpg"
  },
  {
    "id": "mutation",
    "steamApiName": "ACH_MUTATION",
    "name": "Enzymic Mutation",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/5cbba35d4bde209e623c01474a21606d3ad2f05f.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/ee0e5510d49ae1ea5385b51adbf825e0360f2107.jpg",
    "hidden": true
  },
  {
    "id": "killed-lava-flier",
    "steamApiName": "ACH_KILLED_LAVA_FLIER",
    "name": "Jelly Baby",
    "description": "Die to a Lava Flyer",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1e7333288765638c6257242f53f250d4dd392213.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/4dbf2444cd44f0df51743e2596929f2ce80daa58.jpg"
  },
  {
    "id": "saved-church",
    "steamApiName": "ACH_SAVED_CHURCH",
    "name": "You Ever Wonder Why We're Here?",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/782ac0e7b4f80cc7494578c76c559b8b89077fb8.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/00dea95be77a41cde67afc0db3dea6f2ffacd4ee.jpg",
    "hidden": true
  },
  {
    "id": "nullsec-fall",
    "steamApiName": "ACH_NULLSEC_FALL",
    "name": "Watch Your Step",
    "description": "Fall to Your Death in the Null Sector",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/dc9603582e1fd2d1cc080c5c1c380fc2a36d8f84.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/07d961b28969c74af4e05ca18f39345e935ae5f6.jpg"
  },
  {
    "id": "nullsec-entry",
    "steamApiName": "ACH_NULLSEC_ENTRY",
    "name": "Dude, Where's my Map?",
    "description": "Enter the Null Sector",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/6154871ab438a9ee04c6dbf4ba0233087b4ff026.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d817bb72b6a83e06aa90321cd1840d44d1bfe550.jpg"
  },
  {
    "id": "nullsec-time",
    "steamApiName": "ACH_NULLSEC_TIME",
    "name": "Harshest of Conditions",
    "description": "Survive 5 Hours in the Null Sector",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/de075eec14bc5f980dfe020784ba7e38c81e66cf.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/7c830c825596b66f0f4d88608d24464cd533459b.jpg"
  },
  {
    "id": "eat-cake",
    "steamApiName": "ACH_EAT_CAKE",
    "name": "Let Them Eat Cake",
    "description": "Enjoy a Slice of Cake",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/39d5911c885e7f3fbffcde95f4b1fdd729fdf230.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d5b2588940ce2bbbf77857ae535ca3eda0fe3ce5.jpg"
  },
  {
    "id": "equip-arctic",
    "steamApiName": "ACH_EQUIP_ARCTIC",
    "name": "Snow Problem",
    "description": "Wear Arctic Armor in the Arctic",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/98557f7cecb1cc0e1f120ea8e7c7492421415d71.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d0e02d7f8cda9c71ad13d78541010289dacc9993.jpg"
  },
  {
    "id": "equip-wayfarer",
    "steamApiName": "ACH_EQUIP_WAYFARER",
    "name": "No Sweat",
    "description": "Wear Wayfarer Armor in the Desert",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/aff92eb97a407512875ff4c4ee81992400d6211d.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/36a83e0d42492ba744eaa968798bc1abe1e0e429.jpg"
  },
  {
    "id": "equip-ghillie",
    "steamApiName": "ACH_EQUIP_GHILLIE",
    "name": "You Can't See Me",
    "description": "Wear Ghillie Armor in the Forest",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/23feb772828e059ecfe4f7d055803e1a22d9d331.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/32c820f136fef0d6e77ad561e7362077801962da.jpg"
  },
  {
    "id": "equip-sandworm",
    "steamApiName": "ACH_EQUIP_SANDWORM",
    "name": "Who Wore It Better?",
    "description": "Kill a Sandworm While Wearing its Armor",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e494d88f3200a277839ba5b836e0f674fce95688.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d3386e0262a1e44fda556c3854464f858856229b.jpg"
  },
  {
    "id": "equip-scorpion",
    "steamApiName": "ACH_EQUIP_SCORPION",
    "name": "Your Own Worst Enemy",
    "description": "Kill the Giant Scorpion While Wearing its Armor",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/5a7b3d963c8de37ffcbcddb85bf1cfb02f76a749.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/14140810c23dc2855ff984575a08906a7a15fecc.jpg"
  },
  {
    "id": "destroy-drone",
    "steamApiName": "ACH_DESTROY_DRONE",
    "name": "Signal Jammed",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/3564e3710902ffa81f64fa5e6f6b3ff8fb0d22c9.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/4962d0ba650394c4c290782e545e1f4889348085.jpg",
    "hidden": true
  },
  {
    "id": "nullsec-respawn",
    "steamApiName": "ACH_NULLSEC_RESPAWN",
    "name": "Back to Square One",
    "description": "Trigger an Emergency Respawn Pod while in the Null Sector",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/14d3f01e64069349887d7d0fd64aaa5faf81f02e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/df711ab3e680d8735aba45f7089550dc95056701.jpg"
  },
  {
    "id": "nullsec-revived",
    "steamApiName": "ACH_NULLSEC_REVIVED",
    "name": "Nice to Have Friends",
    "description": "Be revived by a Teammate in the Null Sector",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/9cb4fc97956ca48b41c92d493ae26082caeee3d6.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/6247df1833c28b3297403b25b1ba7a1e3edb3ca4.jpg"
  },
  {
    "id": "backpack-cook",
    "steamApiName": "ACH_BACKPACK_COOK",
    "name": "Professional Chef",
    "description": "Cook a Meal While Wearing the Culinex Backpack",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/52fa2719af0a6e9236eada3f3a1a552df493215f.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/b0d7713efb4b56b90b0d4440ebedf536e8ee9567.jpg"
  },
  {
    "id": "prometheus",
    "steamApiName": "ACH_PROMETHEUS",
    "name": "A Gift of Fire",
    "description": "Complete All Six New Frontiers Story Missions",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/308dee1124129e1b959b0046cbfadc31938a98c3.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/ff92f1da220f8583aab2689df0d94a0d4873d7eb.jpg"
  },
  {
    "id": "prometheus-1",
    "steamApiName": "ACH_PROMETHEUS_1",
    "name": "Soft Landing",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/85d9e6b3972a397ca65e15b19210b0a6676dc4b8.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/2a5fc0e1924b8541d5e76bd3b6c9f598fd25fbc4.jpg",
    "hidden": true
  },
  {
    "id": "prometheus-2",
    "steamApiName": "ACH_PROMETHEUS_2",
    "name": "Unknown Caller",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/88a38f0f25503d09868476217ef594490f1a2f2c.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e9af1c71979a30213e9b825e42d6749d2063601b.jpg",
    "hidden": true
  },
  {
    "id": "prometheus-3",
    "steamApiName": "ACH_PROMETHEUS_3",
    "name": "One Of Us",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8060084ea2ca843adcb3e146d1ffa4989eac419e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/88e02ba615324965435bc72345e236c706e4c424.jpg",
    "hidden": true
  },
  {
    "id": "prometheus-4",
    "steamApiName": "ACH_PROMETHEUS_4",
    "name": "Thanks, Buddy",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/98561f4de0410a8aa0eaad66aa449fe72dee7840.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/c69af98d2fbf622944b0a44b8304eb0b4f1c8625.jpg",
    "hidden": true
  },
  {
    "id": "prometheus-5",
    "steamApiName": "ACH_PROMETHEUS_5",
    "name": "That Was Close",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/90e3c5986b3be4f96b499ae7b6ead32469e47ff0.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/b2c1a6d999ada060763df6e49fad7a7c449d991e.jpg",
    "hidden": true
  },
  {
    "id": "prometheus-6",
    "steamApiName": "ACH_PROMETHEUS_6",
    "name": "AWOL",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/355402dacac9a69a946dda9ece21430d072fcee9.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d2264e0bb9bfbc50c0794cccd8752b5492ff3811.jpg",
    "hidden": true
  },
  {
    "id": "prometheus-7",
    "steamApiName": "ACH_PROMETHEUS_7",
    "name": "What is this place?",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/24e2106e03372624e8c96a8e4ea454f0f853e8aa.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/a15367e14ef0794e8ecef06f759135365ab13012.jpg",
    "hidden": true
  },
  {
    "id": "nullsec-story",
    "steamApiName": "ACH_NULLSEC_STORY",
    "name": "Poor Hans",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/3a72bfebaf602c9de9e62fd84b8c3c2cf625affc.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/7e42914a1c48e3749ca262d36b60b687d435346a.jpg",
    "hidden": true
  },
  {
    "id": "daisy",
    "steamApiName": "ACH_DAISY",
    "name": "The Bodyguard",
    "description": "Escort Daisy to Safety",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/aa4fbdb554196c732a58b69655c1cb89a9c9a388.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/74a49ecf620c81d9b4b0cbd4284f8db609893672.jpg"
  },
  {
    "id": "exotics-red",
    "steamApiName": "ACH_EXOTICS_RED",
    "name": "Cha-Ching!",
    "description": "Collect and process 5,000 Red Exotics",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e6422e454273f90a2fefd2f88472f2565ed64dde.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/12b74d8e88602a1e6461103779fe278f3f68064c.jpg"
  },
  {
    "id": "suitup",
    "steamApiName": "ACH_SUITUP",
    "name": "Suited Up",
    "description": "Drop with a Full Set of Armor in Your Loadout",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1352a493c3c05c76af110c5968049401fd552634.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e90dda6905e1d79f5c547e47f8b23c742297cac1.jpg"
  },
  {
    "id": "tame-kill",
    "steamApiName": "ACH_TAME_KILL",
    "name": "Sic 'em!",
    "description": "Your Tamed Pet Makes A Kill",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/3026c7598b9afcda03acf6b3aa43c5c20eefbaa1.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/6189efe2c7592466f1a8d8428b53f247ed025da3.jpg"
  },
  {
    "id": "tame-dies",
    "steamApiName": "ACH_TAME_DIES",
    "name": "RIP Mr Kitty",
    "description": "Your Pet Crosses the Rainbow Bridge",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/0650561d2dee4dcfcf12503663f47bac0d028b0d.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/a87ca7b84b142f3c017b2c8a95ac3032858ae043.jpg"
  },
  {
    "id": "hotandcold",
    "steamApiName": "ACH_HOTANDCOLD",
    "name": "Hot 'n' Cold",
    "description": "Suffer from Frostbite and Heat Exhaustion at the Same Time",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/bb5d49de506b9bcbe5b014b46361575f339fa649.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/df05c7942891d410324e6ab0becd589cc5f8fc18.jpg"
  },
  {
    "id": "tame-hostile",
    "steamApiName": "ACH_TAME_HOSTILE",
    "name": "Easy Tiger",
    "description": "Tame a Hostile Creature",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/f8ae47e602618cb5afbf995067b4e093a850a9f0.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/783b16b4102000bd4731a88a74c0138bf3f81ce7.jpg"
  },
  {
    "id": "swim-in-lava",
    "steamApiName": "ACH_SWIM_IN_LAVA",
    "name": "Hot-hot-hot-hot-hot!",
    "description": "Survive a Swim in Lava",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/5b5ec9e6a0dbf1e5e2224d4d0e2f8cb4f140d402.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/45c40ee5899eecd9910ab5765ef62238f4b2d092.jpg"
  },
  {
    "id": "upgrade-beehive",
    "steamApiName": "ACH_UPGRADE_BEEHIVE",
    "name": "Not the Bees!",
    "description": "Build a Fully Upgraded Beehive",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/5c884f74cfa231309452b4606591cc66f26b6ae3.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8bd1a21526d0222119599e63b4e45e6b3ae7f59e.jpg"
  },
  {
    "id": "tame-level50",
    "steamApiName": "ACH_TAME_LEVEL50",
    "name": "Mountie",
    "description": "Have a level 50 Mount",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1badd23f19e2495d3d1f81232a7b7bb323b6c690.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/af050a3009ba44d0f19f389e9ca985fcca5190e3.jpg"
  },
  {
    "id": "tame-level25",
    "steamApiName": "ACH_TAME_LEVEL25",
    "name": "Fur Baby",
    "description": "Have a level 25 Pet",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/13bac86d13e4f63649720c49e473224fcc5d65d5.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/71e29ad5a6aa322efd5252b180d7a60bf42bb91b.jpg"
  },
  {
    "id": "cozy",
    "steamApiName": "ACH_COZY",
    "name": "So Comfy, Can't Move",
    "description": "Get to Coziness Level 250 when Sleeping",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/222b9e78b0d18f3870e29aa3441e99be681f90e3.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/99812b8e10fa2c3f02e2c3075146961db60cf51c.jpg"
  },
  {
    "id": "resource-packs",
    "steamApiName": "ACH_RESOURCE_PACKS",
    "name": "Gimme Gimme Gimme",
    "description": "Request 100 Resource Packs",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/2eb1462f6e6b7e7a5fe48b8f60e4acc99fc295b3.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/120beb7592266f7f6cc63905e566d05129b23123.jpg"
  },
  {
    "id": "tame-number",
    "steamApiName": "ACH_TAME_NUMBER",
    "name": "Ringleader",
    "description": "Tame 10 Creatures",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1c3ec4be31456ba0f4956afb69c955f1397aeb10.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/297e3921d7872dde055389ccd0845f6b469c74af.jpg"
  },
  {
    "id": "electroshock",
    "steamApiName": "ACH_ELECTROSHOCK",
    "name": "Shocking",
    "description": "Inflict Electroshock on a Wet Target",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/6fb96b726685da1a97f6f911d67664e5f83b2697.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e9c1b0202b62c63be5a1a1684b966158b4c5e9d5.jpg"
  },
  {
    "id": "quests-total",
    "steamApiName": "ACH_QUESTS_TOTAL",
    "name": "UDA Veteran",
    "description": "Complete 50 SMPL3 Missions in an Open World",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d4c6136a93ec5a4398637664f0a3fd33ac5d25a2.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/04e7718dfbda9dc11d2c4f950066dd3ed6b1a0e9.jpg"
  },
  {
    "id": "block-damage",
    "steamApiName": "ACH_BLOCK_DAMAGE",
    "name": "Blocked!",
    "description": "Block 5000 Damage With a Shield",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/ccf407fc4b79251dcfce8a28e3611b812049599d.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/44f8b4b61be218405f5bc66effbf62218ff61374.jpg"
  },
  {
    "id": "sledgehammer",
    "steamApiName": "ACH_SLEDGEHAMMER",
    "name": "Crushing It",
    "description": "Break Rocks With a Sledgehammer",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/c24c7b3d2e37e69d8e7604b79d042f2768b399e7.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/841c28b05382967f138099d8fcdd13dc0c3ab936.jpg"
  },
  {
    "id": "fall-survive",
    "steamApiName": "ACH_FALL_SURVIVE",
    "name": "What Fall Damage?",
    "description": "Survive a Terrible Fall",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/c7d8e2141ab65179c926bbb79ea69b135831d677.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/c4915ab4a1bdc2c116e52f9a6be1bb9cd498fbbf.jpg"
  },
  {
    "id": "meteor-event",
    "steamApiName": "ACH_METEOR_EVENT",
    "name": "Starstruck",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/ced021072a889997ab9dc2a314d4c7ff3c48e522.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/5559c9b796b500f000670c7dfa79d9150fa9a944.jpg",
    "hidden": true
  },
  {
    "id": "outpost-builder",
    "steamApiName": "ACH_OUTPOST_BUILDER",
    "name": "Outpost Builder",
    "description": "Build an Outpost Base Using at Least 50 Pieces",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/12010a82eea8376b3d17575b5c3b8d2d90ae43b2.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/366e472cfdbf8580d89eb71f58341497d8661c06.jpg"
  },
  {
    "id": "outpost-time",
    "steamApiName": "ACH_OUTPOST_TIME",
    "name": "Outpost Veteran",
    "description": "Spend 10 Hours Exploring Your Outpost",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/3cfdc0dd86de2c27e2f8a51ef0d9f4399f922871.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/0b2a6e50b877a3e46542b460bc99fa66278866d0.jpg"
  },
  {
    "id": "kill-bear-hands",
    "steamApiName": "ACH_KILL_BEAR_HANDS",
    "name": "Bear Hands",
    "description": "Defeat a Bear Using Your Fists",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d27d6d53f84a813f99f960c6fd82d25529386bdb.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/465e5e34b924419c9401c41907637b8b8f4ee641.jpg"
  },
  {
    "id": "tame-order-horse",
    "steamApiName": "ACH_TAME_ORDER_HORSE",
    "name": "Hay There, Neigh-bor!",
    "description": "Bring Down a Horse From the Workshop",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/9e0a902c243d0e99803ac3c02894d6e8c3f7f383.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e0d1352dfcfc0d0fefd08dd40e82960d43443b6e.jpg"
  },
  {
    "id": "tame-home",
    "steamApiName": "ACH_TAME_HOME",
    "name": "Habitat Acquired",
    "description": "Build a Home for Your New Pet With Bedding, Food, and Water",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8a6e6fc2bde08e34bc9df29b6b7fafe42f25d0a3.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e45aefae792fba98cd0adef364bcc4cdf4607fa9.jpg"
  },
  {
    "id": "tame-order-chicken",
    "steamApiName": "ACH_TAME_ORDER_CHICKEN",
    "name": "Cock-a-Doodle-Doom",
    "description": "Bring Down a Chicken From the Workshop",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/97208caf8bfe3d93ee3fee1c055c40b0f2a64a97.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8b1e63c6b11121321eaf61ba85afe21dca3ad399.jpg"
  },
  {
    "id": "tame-order-cat",
    "steamApiName": "ACH_TAME_ORDER_CAT",
    "name": "Cat-astrophy Averted",
    "description": "Bring Down a Cat From the Workshop",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/831a61e0267429f318b51459630f7ec7eac58dbb.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/648976ea8e7604035f02f8cf9790d57361af5431.jpg"
  },
  {
    "id": "tame-order-dog",
    "steamApiName": "ACH_TAME_ORDER_DOG",
    "name": "Barking Up the Right Tree",
    "description": "Bring Down a Dog From the Workshop",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d2f684fa171f153a5dad5036de1dbe7e162e1a4c.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/6ebe34cd0e3221e400b78766da4e23d680b3db54.jpg"
  },
  {
    "id": "play-fetch",
    "steamApiName": "ACH_PLAY_FETCH",
    "name": "No Take, Only Throw",
    "description": "Play Fetch With Your Dog",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/76272198ed77d3d2179636299b23e7f320b80658.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8fa1530ff52d8aa0023d960466fb1471bc857400.jpg"
  },
  {
    "id": "breakfast",
    "steamApiName": "ACH_BREAKFAST",
    "name": "The Most Important Meal of the Day",
    "description": "Eat a Big Breakfast, in the Morning, When Well Rested",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/bc7f25d8bd57c1a4ed56a1589591c7a3446b27b9.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/196fdcfa6ffe283473714ece6957da13e3e8b22a.jpg"
  },
  {
    "id": "advanced-technology",
    "steamApiName": "ACH_ADVANCED_TECHNOLOGY",
    "name": "Advanced Technology",
    "description": "Mine using a Mining Laser",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d5bf479f38fc316477461d288fbbb696bf49fc06.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/66e12836c6e8c4ce76370476102492747cc2c84c.jpg"
  },
  {
    "id": "and-you-are",
    "steamApiName": "ACH_AND_YOU_ARE",
    "name": "And You Are?",
    "description": "Introduce yourself to the members of TEI",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/19ce7ac40747cc6471799751bcc0e5b41b91c6ed.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/fca5c07b405738528acc41a47d575ae60f1f1dee.jpg"
  },
  {
    "id": "at-all-costs",
    "steamApiName": "ACH_AT_ALL_COSTS",
    "name": "At All Costs",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e07651e9092d2c0b3e70ed23bd839243b99a783c.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/0d13884be28d6dddb6de8fc544777f8138a1b3fe.jpg",
    "hidden": true
  },
  {
    "id": "biochemical-warfare",
    "steamApiName": "ACH_BIOCHEMICAL_WARFARE",
    "name": "Biochemical Warfare",
    "description": "Kill a creature with Uranium Ammo",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/7e8a51864e2f0e4528b8bbf4481509459ab151cb.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/b2e5707d03946620fff3046b561cccf729f6547a.jpg"
  },
  {
    "id": "burn-notice",
    "steamApiName": "ACH_BURN_NOTICE",
    "name": "Burn Notice",
    "description": "Have a Flamethrower Turret Defeat an Enemy",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/9a16b0ebb6f086119caf87d047e05095146db06a.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1b71b138f233031651cc7af2f1fb484dbf197337.jpg"
  },
  {
    "id": "crude-awakening",
    "steamApiName": "ACH_CRUDE_AWAKENING",
    "name": "Crude Awakening",
    "description": "Build and Place a Crude Oil Power Generator",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/efb78436eb49713f72f1b5f9f0b343929522d66a.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/3cb797c9d4dac8b11059b50c9f8b48e7e604689b.jpg"
  },
  {
    "id": "deceit",
    "steamApiName": "ACH_DECEIT",
    "name": "Deceit",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8b7111e9d8b77d3c7344f38851bd86cee5f18607.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/3f055a6e23a239e71993ede75f28ac7539d1aacd.jpg",
    "hidden": true
  },
  {
    "id": "home-sweet-home",
    "steamApiName": "ACH_HOME_SWEET_HOME",
    "name": "Home Sweet Home",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e7ced88d2f7820d0c4c00afd9f964b03ef92399a.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/9cb2b5838beb02d409ce56a635831ddb20ff6f95.jpg",
    "hidden": true
  },
  {
    "id": "drill-baby-drill",
    "steamApiName": "ACH_DRILL_BABY_DRILL",
    "name": "Drill Baby Drill",
    "description": "Generate Refined Oil from a Crude Oil Refiner",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/193c1e6d40f1c1ed87d2598509deac083003727e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1161fddc443b527f69c08111f74b43038857220b.jpg"
  },
  {
    "id": "encrypted",
    "steamApiName": "ACH_ENCRYPTED",
    "name": "Encrypted",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e7d3b89f9d285972b6286a25bfc62008336d46e8.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8a9c197c0cc3dba686653baf21b3bb49a7a6cf25.jpg",
    "hidden": true
  },
  {
    "id": "eris-inquisition",
    "steamApiName": "ACH_ERIS_INQUISITION",
    "name": "The Eris Inquisition",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/5832f34acf5f16a4717493e6402298cb322d19fc.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/248ec2f523685dbf5c038f26846a8238a875117c.jpg",
    "hidden": true
  },
  {
    "id": "eyes-on-me",
    "steamApiName": "ACH_EYES_ON_ME",
    "name": "Eyes On Me",
    "description": "Tame a Storca",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d7d5fe6daf45d3417cf3720d23071cc9dc95f748.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/4f059ce90307ebe98d51c5032a3a9ee04e51dce7.jpg"
  },
  {
    "id": "for-mo",
    "steamApiName": "ACH_FOR_MO",
    "name": "For Mo",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/413015b044b1c26ef3ed84fc214ef9c7cc03e495.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/b19e07f24e67956229fbc7650bc1d44be6e11027.jpg",
    "hidden": true
  },
  {
    "id": "future-oil-baron",
    "steamApiName": "ACH_FUTURE_OIL_BARON",
    "name": "Future Oil Baron",
    "description": "Find and use an oil geyser",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/f0da341e2d726f12cabf60b44e58fe1b7068f37d.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/48933bb20e2c1e9a0d9964a53cff372de7bc9449.jpg"
  },
  {
    "id": "ghosted",
    "steamApiName": "ACH_GHOSTED",
    "name": "Ghosted",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/edf318086c2f80d3cdd59aaa9da1e064e113c59f.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/4084f5e52352d3cc8d32057d5340b98b1292faf8.jpg",
    "hidden": true
  },
  {
    "id": "glow-up",
    "steamApiName": "ACH_GLOW_UP",
    "name": "Glow-Up",
    "description": "Wear a Hazmat Suit in a Radioactive Zone",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/cdcd19d3c5a041be13ea88fc3bd9292141dd0b6f.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e37c375fc8600fcb3027d9a84b636d22413f7650.jpg"
  },
  {
    "id": "gone-fission",
    "steamApiName": "ACH_GONE_FISSION",
    "name": "Gone Fission",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/0ebc3b2fb8c8068206cf275fecaa810d00450a73.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/ade85dc6c2240f2f0addce1857b602c995f7fb6f.jpg",
    "hidden": true
  },
  {
    "id": "complete-bestiary-elysium",
    "steamApiName": "ACH_COMPLETE_BESTIARY_ELYSIUM",
    "name": "Gotta Catch Them All II",
    "description": "Max Rank Elysium Creatures in the Bestiary",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/36a68dcefee315fe17c0b7d4343434138aa99af3.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/9574b1649515be167b3507bb67624a49d25b8f09.jpg"
  },
  {
    "id": "graceful-landing",
    "steamApiName": "ACH_GRACEFUL_LANDING",
    "name": "Graceful Landing",
    "description": "Drop into Elysium for the first time",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/10b1e6bbfb0f0770ea61620b1d49806ba271f6a0.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/9ca4deb61f694e0ece92d74cd6da1d5354aac96b.jpg"
  },
  {
    "id": "handy",
    "steamApiName": "ACH_HANDY",
    "name": "Handy",
    "description": "Create a Portable Battery",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d114a63db6722839931d68a5b27b9a4860d2a52d.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/52cd3d07a44f89cd0613608a5e73656c7d47cf8e.jpg"
  },
  {
    "id": "hard-reset",
    "steamApiName": "ACH_HARD_RESET",
    "name": "Hard Reset",
    "description": "Destroy a Drone Spawner with a Sledgehammer",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/aeb2b61470db61ab78db66f5efc373f9bd9b0be5.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/d3c007d6da6bad8ff79eed1a3b3dc6848e1b4fd8.jpg"
  },
  {
    "id": "heavy-metal-remix",
    "steamApiName": "ACH_HEAVY_METAL_REMIX",
    "name": "Heavy Metal Remix",
    "description": "Convert Inert Uranium into Platinum or Titanium",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/b8b7548a6285b46050b13cfe987a610f2c5ed9ab.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e44d2879de19282ff39c3e0a161ea52b179f3e09.jpg"
  },
  {
    "id": "industrial-stapling",
    "steamApiName": "ACH_INDUSTRIAL_STAPLING",
    "name": "Industrial Stapling",
    "description": "Use a Nailgun to Repair a Structure",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/4907cc09f64999dc1c441dd95b996a50ca4b70cf.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8eb5ff3440fa4c71732e82c4675557711dcb0337.jpg"
  },
  {
    "id": "jurassic-perks",
    "steamApiName": "ACH_JURASSIC_PERKS",
    "name": "Jurassic Perks",
    "description": "Tame a Raptor",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1989b783f5c592688332b42d73c9236531ee8571.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8339ca59ad5ef1c79e8be034edc84390c22eb7c1.jpg"
  },
  {
    "id": "lab-rat",
    "steamApiName": "ACH_LAB_RAT",
    "name": "Lab Rat",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/7b3b641ca98f4a0a38f914b43f1a694a23660dd5.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/9e9f55099836d04b774c017e76ff68be85bc2b6f.jpg",
    "hidden": true
  },
  {
    "id": "mass-production",
    "steamApiName": "ACH_MASS_PRODUCTION",
    "name": "Mass Production",
    "description": "Unlock the Manufacturer",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/e01ecb6ef576e1f425a4bbeaf39133364f96914e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/816b7471b28f91e3366a7a955b6fbea6944567ab.jpg"
  },
  {
    "id": "mushrooms",
    "steamApiName": "ACH_MUSHROOMS",
    "name": "Mushrooms?",
    "description": "Find the Mushroom Swamp",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/61cb1d5f4c8b3bfa82129a78286034b4acbdb6c3.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8a345b62c2a3cdf99c1fab51d34131878c281dcc.jpg"
  },
  {
    "id": "new-horizons",
    "steamApiName": "ACH_NEW_HORIZONS",
    "name": "Serene Stench",
    "description": "Enter the Geothermal Biome",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/0493d1c869eee62d70d285e037030c12ac0031f6.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/80055052dc4d16b1456d6d99bd92250200229d6d.jpg"
  },
  {
    "id": "nice-ride",
    "steamApiName": "ACH_NICE_RIDE",
    "name": "Nice Ride",
    "description": "Ride a Raptor",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/83de24f42cfc909d6d40d87588ccdea3658b9a62.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/7c81c5fef56a95e2ed7178ab5b7836bce733e3a5.jpg"
  },
  {
    "id": "off-the-charts",
    "steamApiName": "ACH_OFF_THE_CHARTS",
    "name": "Off the Charts",
    "description": "Collect and process 5,000 Enriched Uranium Rods",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/4182edaf46b48872a08102130ad0325e48dc6466.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/6a3d570cc3064166ca5bb6cc53b1430e69e45db2.jpg"
  },
  {
    "id": "pack-mule",
    "steamApiName": "ACH_PACK_MULE",
    "name": "Pack Mule",
    "description": "Tame a Draven",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/adce3b864efe40d7bf916a7fb334d728b1ec05da.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1c3fbb4d9204ce88ef528452d4674b98d68055e8.jpg"
  },
  {
    "id": "peak-tech",
    "steamApiName": "ACH_PEAK_TECH",
    "name": "Peak Tech",
    "description": "Unlock all Blueprints in Tier 5",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8210c1a1f2c18dc779f3d9c6804e6c02faf29e69.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/7a5d0b55b6611a314924fa713ceb3cf13ca26373.jpg"
  },
  {
    "id": "pew-pew-pew",
    "steamApiName": "ACH_PEW_PEW_PEW",
    "name": "Pew Pew Pew",
    "description": "Acquire a Laser Sidearm",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/b592b87ff995d4b07f1cc260b0c98fc8a3071c38.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1b040135dd78dded2c052442a8063694bd1ca91a.jpg"
  },
  {
    "id": "pew-review",
    "steamApiName": "ACH_PEW_REVIEW",
    "name": "Pew Review",
    "description": "Modify a Laser Sidearm",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8111460119866b5aea684893d7cbc09365370ccf.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/9ee3c24676670f2d1613d2aceec1cc2c34297635.jpg"
  },
  {
    "id": "pinnacle-of-his-career",
    "steamApiName": "ACH_PINNACLE_OF_HIS_CAREER",
    "name": "Pinnacle of his Career",
    "description": "Have a Tesla Coil Defeat an Enemy",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/a3ccefdf6c500e2d01590575b7a6a3ea8dd62e43.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/67fc15741dbde567927a68c6048eddff8a85048a.jpg"
  },
  {
    "id": "plot-armor",
    "steamApiName": "ACH_PLOT_ARMOR",
    "name": "Plot Armor",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/2d2290110dc60041da0dff3c210e08fe68a0159a.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/f638da542a170aa2f172be9cde051950216cc4d4.jpg",
    "hidden": true
  },
  {
    "id": "power-trip",
    "steamApiName": "ACH_POWER_TRIP",
    "name": "Power Trip",
    "description": "Charge a Lithium Tool",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/49cf502d235d9063ddb7115b2b50fe796baf9166.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/b94be5d176fc7b0d48b53ed19432ec12f5a30411.jpg"
  },
  {
    "id": "read-the-room",
    "steamApiName": "ACH_READ_THE_ROOM",
    "name": "Read the Room",
    "description": "Use a Geiger Counter",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/2b464cb5e42e185601a39be2ec9284ced1f91619.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/5258e721fd8dc75da66c5fe873a9060d3260c226.jpg"
  },
  {
    "id": "rock-out",
    "steamApiName": "ACH_ROCK_OUT",
    "name": "Rock Out",
    "description": "Use a Jackhammer on an Ore",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/f7fa504615ce0a381fa7e4f14b05f173ed14235e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/2385c638ac8c266fae82af58eab0fc8ade0e97c8.jpg"
  },
  {
    "id": "rock-solid",
    "steamApiName": "ACH_ROCK_SOLID",
    "name": "Rock Solid",
    "description": "Build and place Concrete or Stone Fortifications",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/37eaf8754fee2b0fafa1ee353301c41c1f08ef4e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/fe7460a25cb73860fa419a7619136cbbc16e5c9f.jpg"
  },
  {
    "id": "royal-decree",
    "steamApiName": "ACH_ROYAL_DECREE",
    "name": "Royal Decree",
    "description": "Kill the Sandwyrm Queen",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/50f2f9be97365f2f6078c7f1e9547c4659133409.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/a3fd2a8e62e134b14c4f67972f83aab361495d23.jpg"
  },
  {
    "id": "saw-it-coming",
    "steamApiName": "ACH_SAW_IT_COMING",
    "name": "Saw It Coming",
    "description": "Use a Chainsaw on a Tree",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/c9db568ae1f609f06e71b4b3c5e73bbeba0517ea.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/9808f84b7747a92390d385dead2184a236af9253.jpg"
  },
  {
    "id": "skulking-around",
    "steamApiName": "ACH_SKULKING_AROUND",
    "name": "Skulking Around",
    "description": "Tame a Skulk",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/3fe5ba11431e6bdc73ddf75be141b82a6ef0990f.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/baf9d2ab2b61dd2aab2ab596bc51aaa9b5e7b445.jpg"
  },
  {
    "id": "slinky",
    "steamApiName": "ACH_SLINKY",
    "name": "Slinky",
    "description": "Tame a Slinker",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/12cfd03e8179fe1f518018f942a955dd3268ed45.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/13dd5951f54b4764f9c6669e09332022489ce09b.jpg"
  },
  {
    "id": "so-cool",
    "steamApiName": "ACH_SO_COOL",
    "name": "So Cool",
    "description": "Build a Structure with Ice",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/3aeb9dff617519f844132d173f895d19d8e5f258.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/8d15574613a4e9a1f76cf47c622f038cf176e8ac.jpg"
  },
  {
    "id": "the-better-option",
    "steamApiName": "ACH_THE_BETTER_OPTION",
    "name": "The Better Option?",
    "description": "Generate Refined Oil from a Natural Oil Refiner",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/7b6b0b862d4a278195ae35201f17864de9fa02a9.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/09272fd4d04ab35ec98f6a806a58b7e888cb61d5.jpg"
  },
  {
    "id": "the-peoples-syndicate",
    "steamApiName": "ACH_THE_PEOPLES_SYNDICATE",
    "name": "The People's Syndicate",
    "description": "Eliminate 250 Drones",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/cb84c7242ba8195086c7ef0f8606eadd4c670472.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/57d2cd233635c7a59ad79d0446809250cb7185b4.jpg"
  },
  {
    "id": "thermonuclear",
    "steamApiName": "ACH_THERMONUCLEAR",
    "name": "Thermonuclear",
    "description": "",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/04d621cc0018ad5cbd3fed52999a48d38a7c2066.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/a4874447fb933d440fd8a22a7b7b2586fe983216.jpg",
    "hidden": true
  },
  {
    "id": "three-eyed-fish",
    "steamApiName": "ACH_THREE_EYED_FISH",
    "name": "Three Eyed Fish",
    "description": "Build and Place a Nuclear Reactor",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/ca8e667aadca67974acea4e8876e8981579d4f18.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/40c9a8c91868bbe4d030617add0fbb1e43498310.jpg"
  },
  {
    "id": "wyrm-reaper",
    "steamApiName": "ACH_WYRM_REAPER",
    "name": "Wyrm Reaper",
    "description": "Kill the Sandwyrm Queen on Hard",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/bd8bc562a03ef85f16027c9c7300d94aa32fb89e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/9f77ae596b0f9e1fe19c71a8613c05255f4bc352.jpg"
  },
  {
    "id": "youre-glowing",
    "steamApiName": "ACH_YOURE_GLOWING",
    "name": "You're Glowing",
    "description": "Die from Radiation",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/4f196036c20db43e4f107e5257b39725d9da17c6.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/3c37ad988dfc8910e0de6c4aa511464a35685ef5.jpg"
  },
  {
    "id": "you-monster",
    "steamApiName": "ACH_YOU_MONSTER",
    "name": "You Monster",
    "description": "Slaughter an Animal Companion",
    "icon": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/1e63fb3dc287c0d89fbd45bf03250de5ea632a9e.jpg",
    "iconGray": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/1149460/eaf67a17f73b3a59769b0acd4a631569f162d095.jpg"
  }
]
