// Generates src/data/icarus/achievements.ts from the Icarus Steam achievement schema.
//
// Unlike Coral Island (hand-curated), Icarus has 170+ achievements, so we pull the full
// schema (display name, description, icons, hidden flag) straight from Steam. This is a
// one-time / occasional generator — re-run it when the game adds achievements.
//
// The API key is read from process.env (CI secret) or a local .env file; it is NEVER
// written to the output. Usage: node scripts/fetch-icarus.mjs

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

function loadEnv() {
  const env = { ...process.env }
  try {
    const raw = readFileSync(resolve(root, '.env'), 'utf8')
    for (const line of raw.split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/)
      if (m && (env[m[1]] === undefined || env[m[1]] === '')) env[m[1]] = m[2]
    }
  } catch {
    // no .env — rely on process.env
  }
  return env
}

const env = loadEnv()
const KEY = env.STEAM_API_KEY
const APP_ID = env.STEAM_ICARUS_APP_ID || '1149460'

if (!KEY) {
  console.error('❌ Missing STEAM_API_KEY. Set it in .env (or as an env var in CI).')
  process.exit(1)
}

const url =
  `https://api.steampowered.com/ISteamUserStats/GetSchemaForGame/v2/` +
  `?key=${KEY}&appid=${APP_ID}&l=english`

let data
try {
  const res = await fetch(url)
  if (!res.ok) {
    console.error(`❌ Steam API returned HTTP ${res.status}. Check that your key is valid.`)
    process.exit(1)
  }
  data = await res.json()
} catch (err) {
  console.error(`❌ Could not reach the Steam API: ${err.message}`)
  process.exit(1)
}

const list = data?.game?.availableGameStats?.achievements ?? []
if (list.length === 0) {
  console.error('❌ Steam returned no achievements in the schema.')
  process.exit(1)
}

// Turn ACH_KILL_SANDWORM_BOSS -> kill-sandworm-boss; keep ids unique & stable.
const seen = new Set()
function slugFor(apiname) {
  let base = apiname
    .replace(/^ACH[_-]?/i, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  if (!base) base = apiname.toLowerCase()
  let id = base
  let n = 2
  while (seen.has(id)) id = `${base}-${n++}`
  seen.add(id)
  return id
}

const achievements = list.map((a) => ({
  id: slugFor(a.name),
  steamApiName: a.name,
  name: (a.displayName ?? a.name).trim(),
  description: (a.description ?? '').trim(),
  icon: a.icon ?? undefined,
  iconGray: a.icongray ?? undefined,
  hidden: a.hidden === 1 ? true : undefined,
}))

const header =
  `// AUTO-GENERATED by scripts/fetch-icarus.mjs — do not edit by hand.\n` +
  `// Source: Steam achievement schema for Icarus (appid ${APP_ID}).\n` +
  `// Re-run \`node scripts/fetch-icarus.mjs\` to refresh.\n` +
  `import type { IcarusAchievement } from '@/types/icarus'\n\n` +
  `export const icarusAchievements: IcarusAchievement[] = `

mkdirSync(resolve(root, 'src/data/icarus'), { recursive: true })
writeFileSync(
  resolve(root, 'src/data/icarus/achievements.ts'),
  header + JSON.stringify(achievements, null, 2) + '\n',
)

const hidden = achievements.filter((a) => a.hidden).length
console.log(`✅ Wrote src/data/icarus/achievements.ts — ${achievements.length} achievements (${hidden} hidden).`)
