// Fetches the player's achievements for each tracked game from the Steam Web API and
// writes a per-game unlocked.ts (public data: which achievements are unlocked, by
// apiname). Coral Island -> src/data/unlocked.ts, Icarus -> src/data/icarus/unlocked.ts.
//
// The API key is read from process.env (GitHub Actions secret) or a local .env file.
// It is NEVER logged and NEVER written to the output file.
//
// Usage: npm run sync

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

/** Merge process.env with a local .env file (process.env wins). */
function loadEnv() {
  const env = { ...process.env }
  try {
    const raw = readFileSync(resolve(root, '.env'), 'utf8')
    for (const line of raw.split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/)
      if (m && (env[m[1]] === undefined || env[m[1]] === '')) env[m[1]] = m[2]
    }
  } catch {
    // no .env file (e.g. in CI) — rely on process.env
  }
  return env
}

const env = loadEnv()
const KEY = env.STEAM_API_KEY
const STEAM_ID = env.STEAM_ID

if (!KEY || !STEAM_ID) {
  console.error('❌ Missing STEAM_API_KEY or STEAM_ID. Set them in .env (or as env vars in CI).')
  process.exit(1)
}

/** Games we track. Each writes its own unlocked.ts (matched by Steam apiname). */
const GAMES = [
  { name: 'Coral Island', appId: env.STEAM_APP_ID || '1158160', out: 'src/data/unlocked.ts' },
  { name: 'Icarus', appId: env.STEAM_ICARUS_APP_ID || '1149460', out: 'src/data/icarus/unlocked.ts' },
]

async function syncGame({ name, appId, out }) {
  const url =
    `https://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v1/` +
    `?appid=${appId}&key=${KEY}&steamid=${STEAM_ID}&l=english`

  let data
  try {
    const res = await fetch(url)
    if (!res.ok) {
      console.error(`❌ ${name}: Steam API returned HTTP ${res.status}. Check that your key is valid.`)
      return false
    }
    data = await res.json()
  } catch (err) {
    console.error(`❌ ${name}: could not reach the Steam API: ${err.message}`)
    return false
  }

  const stats = data.playerstats
  if (!stats || !stats.success) {
    console.error(`❌ ${name}: Steam returned no achievements: ${stats?.error ?? 'unknown error'}.`)
    console.error('   → Make sure your Steam profile AND game details are set to Public.')
    return false
  }

  const list = stats.achievements ?? []
  const unlockedApiNames = list
    .filter((a) => a.achieved === 1)
    .map((a) => a.apiname)
    .sort()

  const now = new Date().toISOString()
  const ts =
    `// AUTO-GENERATED by scripts/sync-steam.mjs — do not edit by hand.\n` +
    `// Last sync: ${now}\n` +
    `export const lastSynced: string | null = ${JSON.stringify(now)}\n` +
    `export const unlockedApiNames: string[] = ${JSON.stringify(unlockedApiNames, null, 2)}\n`

  mkdirSync(dirname(resolve(root, out)), { recursive: true })
  writeFileSync(resolve(root, out), ts)
  console.log(`✅ ${name}: ${unlockedApiNames.length}/${list.length} unlocked → ${out}`)
  return true
}

let ok = true
for (const game of GAMES) ok = (await syncGame(game)) && ok
if (!ok) process.exit(1)
