// Fetches the player's Coral Island achievements from the Steam Web API and writes
// src/data/unlocked.ts (public data: which achievements are unlocked, by apiname).
//
// The API key is read from process.env (GitHub Actions secret) or a local .env file.
// It is NEVER logged and NEVER written to the output file.
//
// Usage: npm run sync

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

/** Merge process.env with a local .env file (process.env wins). */
function loadEnv() {
  const env = { ...process.env }
  try {
    const raw = readFileSync(resolve(root, '.env'), 'utf8')
    for (const line of raw.split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/)
      if (m && (env[m[1]] === undefined || env[m[1]] === '')) env[m[1]] = m[2]
    }
  } catch {
    // no .env file (e.g. in CI) — rely on process.env
  }
  return env
}

const env = loadEnv()
const KEY = env.STEAM_API_KEY
const STEAM_ID = env.STEAM_ID
const APP_ID = env.STEAM_APP_ID || '1158160'

if (!KEY || !STEAM_ID) {
  console.error('❌ Missing STEAM_API_KEY or STEAM_ID. Set them in .env (or as env vars in CI).')
  process.exit(1)
}

const url =
  `https://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v1/` +
  `?appid=${APP_ID}&key=${KEY}&steamid=${STEAM_ID}&l=english`

let data
try {
  const res = await fetch(url)
  if (!res.ok) {
    console.error(`❌ Steam API returned HTTP ${res.status}. Check that your key is valid.`)
    process.exit(1)
  }
  data = await res.json()
} catch (err) {
  console.error(`❌ Could not reach the Steam API: ${err.message}`)
  process.exit(1)
}

const stats = data.playerstats
if (!stats || !stats.success) {
  console.error(`❌ Steam returned no achievements: ${stats?.error ?? 'unknown error'}.`)
  console.error('   → Make sure your Steam profile AND game details are set to Public.')
  process.exit(1)
}

const list = stats.achievements ?? []
const unlockedApiNames = list
  .filter((a) => a.achieved === 1)
  .map((a) => a.apiname)
  .sort()

const now = new Date().toISOString()
const ts =
  `// AUTO-GENERATED by scripts/sync-steam.mjs — do not edit by hand.\n` +
  `// Last sync: ${now}\n` +
  `export const lastSynced: string | null = ${JSON.stringify(now)}\n` +
  `export const unlockedApiNames: string[] = ${JSON.stringify(unlockedApiNames, null, 2)}\n`

writeFileSync(resolve(root, 'src/data/unlocked.ts'), ts)

console.log(`✅ Synced: ${unlockedApiNames.length}/${list.length} achievements unlocked.`)
console.log('   Wrote src/data/unlocked.ts (matched by Steam apiname).')

// Full apiname <-> display-name reference, for maintaining src/data/achievements.ts.
const reference = list
  .map((a) => ({ apiname: a.apiname, name: a.name, achieved: a.achieved }))
  .sort((a, b) => a.apiname.localeCompare(b.apiname))
console.log('REFERENCE_JSON=' + JSON.stringify(reference))
