import type { CollectionItem } from '@/types/achievement'

// AUTO-GENERATED by scripts/fetch-collection.mjs (Category:Monsters) — 24 items.
// Source: Coral Island Wiki (Fandom). Images hotlinked from the Fandom CDN.
export const enemyTypes: CollectionItem[] = [
  { id: 'advanced-slime', name: "Advanced Slime", image: "https://static.wikia.nocookie.net/coralisland/images/0/0e/Advanced_Slime_icon.png/revision/latest?cb=20230802020659" },
  { id: 'amalo', name: "Amalo", image: "https://static.wikia.nocookie.net/coralisland/images/a/aa/Amalo_icon.png/revision/latest?cb=20230802020704" },
  { id: 'armulite', name: "Armulite", image: "https://static.wikia.nocookie.net/coralisland/images/8/8e/Armulite_icon.png/revision/latest?cb=20230802020716" },
  { id: 'bronze-tuku-tuku', name: "Bronze Tuku - Tuku", image: "https://static.wikia.nocookie.net/coralisland/images/0/00/Tuku_Tuku_Bronze_icon.png/revision/latest?cb=20230802020802" },
  { id: 'earth-skully', name: "Earth Skully", image: "https://static.wikia.nocookie.net/coralisland/images/a/ac/Skully_Earth_icon.png/revision/latest?cb=20230802020728" },
  { id: 'earth-slime', name: "Earth Slime", image: "https://static.wikia.nocookie.net/coralisland/images/9/9e/Slime_Earth_icon.png/revision/latest?cb=20230802020735" },
  { id: 'fire-skully', name: "Fire Skully", image: "https://static.wikia.nocookie.net/coralisland/images/a/a7/Skully_Fire_icon.png/revision/latest?cb=20230802020729" },
  { id: 'fire-slime', name: "Fire Slime", image: "https://static.wikia.nocookie.net/coralisland/images/2/24/Slime_Fire_icon.png/revision/latest?cb=20230802020736" },
  { id: 'gold-tuku-tuku', name: "Gold Tuku - Tuku", image: "https://static.wikia.nocookie.net/coralisland/images/2/2c/Tuku_Tuku_Gold_icon.png/revision/latest?cb=20230802020804" },
  { id: 'ombuto', name: "Ombuto", image: "https://static.wikia.nocookie.net/coralisland/images/6/63/Ombuto_icon.png/revision/latest?cb=20230802020717" },
  { id: 'osmium-tuku-tuku', name: "Osmium Tuku - Tuku", image: "https://static.wikia.nocookie.net/coralisland/images/f/f6/Tuku_Tuku_Osmium_icon.png/revision/latest?cb=20230802020805" },
  { id: 'pickling', name: "Pickling", image: "https://static.wikia.nocookie.net/coralisland/images/5/52/Pickling_icon.png/revision/latest?cb=20230802020723" },
  { id: 'silver-tuku-tuku', name: "Silver Tuku - Tuku", image: "https://static.wikia.nocookie.net/coralisland/images/2/24/Tuku_Tuku_Silver_icon.png/revision/latest?cb=20230802020807" },
  { id: 'simple-slime', name: "Simple Slime", image: "https://static.wikia.nocookie.net/coralisland/images/3/3e/Slime_icon.png/revision/latest?cb=20230802020738" },
  { id: 'skully', name: "Skully", image: "https://static.wikia.nocookie.net/coralisland/images/c/cc/Skully_icon.png/revision/latest?cb=20240823220350" },
  { id: 'snatcher', name: "Snatcher", image: "https://static.wikia.nocookie.net/coralisland/images/9/96/Snatcher_icon.png/revision/latest?cb=20230802020747" },
  { id: 'sphekter', name: "Sphekter", image: "https://static.wikia.nocookie.net/coralisland/images/d/d7/Sphekter_icon.png/revision/latest?cb=20230802020757" },
  { id: 'spider', name: "Spider", image: "https://static.wikia.nocookie.net/coralisland/images/8/84/Spider.png/revision/latest?cb=20231120174158" },
  { id: 'the-bat-dude', name: "The Bat Dude", image: "https://static.wikia.nocookie.net/coralisland/images/6/6d/Bat_icon.png/revision/latest?cb=20230919191809" },
  { id: 'tuku-tuku', name: "Tuku - Tuku", image: "https://static.wikia.nocookie.net/coralisland/images/0/03/Tuku_Tuku_icon.png/revision/latest?cb=20230802020809" },
  { id: 'water-skully', name: "Water Skully", image: "https://static.wikia.nocookie.net/coralisland/images/7/71/Skully_Water_icon.png/revision/latest?cb=20230802020731" },
  { id: 'water-slime', name: "Water Slime", image: "https://static.wikia.nocookie.net/coralisland/images/a/af/Slime_Water_icon.png/revision/latest?cb=20230802020740" },
  { id: 'wind-skully', name: "Wind Skully", image: "https://static.wikia.nocookie.net/coralisland/images/1/14/Skully_Wind_icon.png/revision/latest?cb=20230802020733" },
  { id: 'wind-slime', name: "Wind Slime", image: "https://static.wikia.nocookie.net/coralisland/images/1/11/Slime_Wind_icon.png/revision/latest?cb=20230802020741" },
]
