import type { Collection } from '@/types/achievement'
import { craftables } from './items/craftables'
import { fish } from './items/fish'
import { insects } from './items/insects'
import { crops } from './items/crops'
import { animalProducts } from './items/animal-products'
import { recipes } from './items/recipes'
import { clothing } from './items/clothing'
import { artifacts } from './items/artifacts'
import { gems } from './items/gems'
import { seaCritters } from './items/sea-critters'
import { fossils } from './items/fossils'
import { artisan } from './items/artisan'
import { foraged } from './items/foraged'
import { mastery } from './items/mastery'
import { townies } from './items/townies'
import { dinosaurs } from './items/dinosaurs'
import { enemyTypes } from './items/enemy-types'

/**
 * Item lists behind the collection achievements.
 *
 * Discrete lists live in src/data/items/ and are generated by scripts/fetch-collection.mjs
 * from the Coral Island wiki. "Union" achievements (museum, legendary-farmer) use
 * `composedOf` to roll up several constituent collections instead of a hand-listed set.
 * Some collections (fossils, artisan, foraged) exist only as union constituents and have
 * no achievement of their own.
 */
export const collections: Collection[] = [
  { key: 'bugs', label: 'Bugs', items: insects },
  { key: 'fish', label: 'Fish', items: fish },
  { key: 'sea-critters', label: 'Sea critters', items: seaCritters },
  {
    key: 'museum',
    label: 'Museum',
    items: [],
    // Paleontology section = the Dinosaurs collection (Paleontologist achievement),
    // since completing it means all fossil pieces were donated. Using raw 'fossils'
    // would show 0/61 because we have no per-fossil donation signal from the save.
    composedOf: ['fish', 'bugs', 'sea-critters', 'gems', 'artifacts', 'dinosaurs'],
  },
  { key: 'artifacts', label: 'Artifacts', items: artifacts },
  { key: 'gems', label: 'Gems', items: gems },
  { key: 'dinosaurs', label: 'Dinosaurs', items: dinosaurs },
  { key: 'townies-hearts', label: 'Townies — hearts (lvl 8)', items: townies },
  { key: 'townies-gifts', label: 'Townies — gifted', items: townies },
  { key: 'crops', label: 'Crops', items: crops },
  { key: 'animal-products', label: 'Animal products', items: animalProducts },
  { key: 'craftables', label: 'Craftables', items: craftables },
  { key: 'recipes', label: 'Recipes', items: recipes },
  { key: 'clothing', label: 'Clothing', items: clothing },
  { key: 'enemy-types', label: 'Enemy types', items: enemyTypes },
  {
    key: 'legendary-farmer',
    label: 'Legendary Farmer (Produce + Caught + Found)',
    items: [],
    // "Ship all journal items" — rolls up by SHIPPED status (from the save), not caught/collected.
    composedMode: 'shipped',
    composedOf: [
      'crops',
      'animal-products',
      'artisan',
      'fish',
      'bugs',
      'sea-critters',
      'foraged',
      'gems',
      'artifacts',
    ],
  },
  { key: 'mastery', label: 'Mastery (lvl 10 in all skills)', items: mastery },

  // Constituent-only collections (no achievement of their own; used by the unions above).
  { key: 'fossils', label: 'Fossils', items: fossils },
  { key: 'artisan', label: 'Artisan goods', items: artisan },
  { key: 'foraged', label: 'Foraged', items: foraged },
]

export const collectionsByKey: Record<string, Collection> = Object.fromEntries(
  collections.map((c) => [c.key, c] as [string, Collection]),
)
