// AUTO-GENERATED by scripts/import-save.mjs from the local Coral Island save — do not edit.
// Last import: 2026-06-09T20:58:51.850Z
export interface SaveProgress {
  lastImported: string | null
  lifetimeEarnings: number | null
  maxCropShipped: number | null
  maxAnimalProductShipped: number | null
  /** collectionKey -> item slugs marked done from the save */
  checked: Record<string, string[]>
  /** per-item ship totals (sorted desc) for the Specialty achievements */
  shipped: { crops: { name: string; count: number }[]; animalProducts: { name: string; count: number }[] }
  /** slugs of every item shipped at least once (Legendary Farmer) */
  shippedSlugs: string[]
}

export const saveProgress: SaveProgress = {
  "lastImported": "2026-06-09T20:58:51.850Z",
  "lifetimeEarnings": 7786662,
  "maxCropShipped": 1096,
  "maxAnimalProductShipped": 611,
  "checked": {
    "fish": [
      "angelfish",
      "arapaima",
      "archer",
      "asian-sheepshead",
      "barracuda",
      "barramundi",
      "black-phantom-ghost-fish",
      "blue-tang",
      "bluegill",
      "boxfish",
      "brown-trout",
      "catfish",
      "chub",
      "clownfish",
      "cobia",
      "cod",
      "crab",
      "crayfish",
      "damselfish",
      "firefish",
      "flameback-fish",
      "freshwater-eel",
      "frogfish",
      "gator-gar",
      "giant-mudskipper",
      "giant-sea-bass",
      "giant-snakehead",
      "giant-stingray",
      "golden-gar",
      "goldfish",
      "great-white-shark",
      "green-sawfish",
      "grouper",
      "hammerhead",
      "jellyfish",
      "koi",
      "lionfish",
      "lobster",
      "mackerel",
      "mandarin",
      "monkfish",
      "octopus",
      "parrotfish",
      "pink-snapper",
      "polka-dot-batfish",
      "pufferfish",
      "rainbow-fish",
      "raja-ampat-shark",
      "red-king-arowana",
      "red-snapper",
      "ruby-red-dragonet",
      "salmon",
      "sardines",
      "sea-cucumber",
      "shrimp",
      "silver-arowana",
      "snakehead",
      "sockeye-salmon",
      "squid",
      "sturgeon",
      "swordfish",
      "tiger-barb",
      "tilapia",
      "tuna",
      "yellow-moray-eel",
      "yellowfin-tuna",
      "yellowtail",
      "zebra-fish"
    ],
    "bugs": [
      "assam-silk-moth",
      "atlas-moth",
      "banded-woollybear",
      "birdwing-butterfly",
      "cecropia-caterpillar",
      "centipede",
      "cricket",
      "crowned-hairstreak-butterfly",
      "dragonfly",
      "eastern-black-swallowtail",
      "firefly",
      "fly",
      "ghost-mantis",
      "grasshopper",
      "ground-beetle",
      "gulf-fritillary",
      "harpalus-beetle",
      "hickory-horned-devil",
      "janetta-forester-butterfly",
      "lady-beetle",
      "leaf-beetle",
      "little-wood-satyr-butterfly",
      "luna-moth",
      "magnolia-green-jumper",
      "man-faced-stink-bug",
      "maple-leafcutter-moth",
      "monarch-caterpillar",
      "moth",
      "olivewing-butterfly",
      "orchid-mantis",
      "pine-sphinx",
      "pipevine-swallowtail-butterfly",
      "polyphemus-moth",
      "praying-mantis",
      "puss-moth",
      "red-admiral",
      "rove-beetle",
      "saddleback",
      "scarites-beetle",
      "snail",
      "soldier-beetle",
      "spicebush-swallowtail-butterfly",
      "striped-garden-caterpillar",
      "tarantula",
      "tiger-beetle",
      "tiger-swallowtail-butterfly",
      "violin-beetle",
      "wasp",
      "western-tiger-swallowtail",
      "widow-spider",
      "wolf-spider",
      "yucca-moth"
    ],
    "sea-critters": [
      "arrow-crab",
      "atolla-jellyfish",
      "bloodbelly-comb-jellyfish",
      "blue-crab",
      "blue-lobster",
      "blue-starfish",
      "brisingida-starfish",
      "calico-lobster",
      "cannonball-jellyfish",
      "cauliflower-jellyfish",
      "chambered-nautilus",
      "common-starfish",
      "cotton-candy-lobster",
      "crown-of-thorns-starfish",
      "eight-armed-sea-star",
      "flowerhat-jellyfish",
      "fuschia-flatworm",
      "giant-isopod",
      "giraffe-seahorse",
      "harlequin-shrimp",
      "hedgehog-seahorse",
      "hermit-crab",
      "horseshoe-crab",
      "jayakar-seahorse",
      "leafy-sea-dragon",
      "mantis-shrimp",
      "mauve-stinger-jellyfish",
      "pink-meanie-jellyfish",
      "pom-pom-crab",
      "red-knob-starfish",
      "ruby-seadragon",
      "sea-anemone",
      "sea-slug",
      "sexy-shrimp",
      "shiho-seahorse",
      "skunk-cleaner-shrimp",
      "split-colored-lobster",
      "stone-crab",
      "sunflower-sea-star",
      "tigertail-seahorse",
      "upside-down-jellyfish",
      "venuss-flower-basket",
      "whelk",
      "white-spotted-jellyfish",
      "yeti-crab"
    ],
    "craftables": []
  },
  "shipped": {
    "crops": [
      {
        "name": "Strawberry",
        "count": 1096
      },
      {
        "name": "Hot Pepper",
        "count": 1020
      },
      {
        "name": "Cranberry",
        "count": 166
      },
      {
        "name": "Pumpkin",
        "count": 90
      },
      {
        "name": "Sugarcane",
        "count": 68
      },
      {
        "name": "Cauliflower",
        "count": 58
      },
      {
        "name": "Radish",
        "count": 40
      },
      {
        "name": "Turnip",
        "count": 36
      },
      {
        "name": "Daisy",
        "count": 34
      },
      {
        "name": "Carrot",
        "count": 30
      },
      {
        "name": "Potato",
        "count": 22
      },
      {
        "name": "Orchid",
        "count": 16
      },
      {
        "name": "Sweet Potato",
        "count": 14
      },
      {
        "name": "Gardenia",
        "count": 12
      },
      {
        "name": "Melon",
        "count": 12
      },
      {
        "name": "Peony",
        "count": 8
      },
      {
        "name": "Blueberry",
        "count": 8
      },
      {
        "name": "Banana",
        "count": 8
      },
      {
        "name": "Iris",
        "count": 6
      },
      {
        "name": "Bell pepper",
        "count": 4
      },
      {
        "name": "Plum",
        "count": 4
      },
      {
        "name": "Snowdrop",
        "count": 4
      },
      {
        "name": "Watermelon",
        "count": 4
      },
      {
        "name": "Tomato",
        "count": 4
      },
      {
        "name": "Starfruit",
        "count": 4
      },
      {
        "name": "Blackberry",
        "count": 4
      },
      {
        "name": "Coffee Beans",
        "count": 4
      },
      {
        "name": "Red Cabbage",
        "count": 4
      },
      {
        "name": "Pineapple",
        "count": 4
      },
      {
        "name": "Corn",
        "count": 4
      },
      {
        "name": "Sunflower",
        "count": 2
      },
      {
        "name": "Papaya",
        "count": 2
      },
      {
        "name": "Rambutan",
        "count": 2
      },
      {
        "name": "Fairy Rose",
        "count": 2
      },
      {
        "name": "Garlic",
        "count": 2
      },
      {
        "name": "Grape",
        "count": 2
      }
    ],
    "animalProducts": [
      {
        "name": "Large milk",
        "count": 611
      },
      {
        "name": "Large egg",
        "count": 230
      },
      {
        "name": "Milk",
        "count": 214
      },
      {
        "name": "Large golden egg",
        "count": 142
      },
      {
        "name": "Large feather",
        "count": 142
      },
      {
        "name": "Large duck egg",
        "count": 130
      },
      {
        "name": "Large wool",
        "count": 100
      },
      {
        "name": "Egg",
        "count": 72
      },
      {
        "name": "Goat milk",
        "count": 62
      },
      {
        "name": "Large gesha coffee bean",
        "count": 44
      },
      {
        "name": "Duck egg",
        "count": 42
      },
      {
        "name": "Large quail egg",
        "count": 24
      },
      {
        "name": "Gesha coffee bean",
        "count": 18
      },
      {
        "name": "Feather",
        "count": 14
      },
      {
        "name": "Quail egg",
        "count": 14
      },
      {
        "name": "Llama wool",
        "count": 10
      },
      {
        "name": "Large llama wool",
        "count": 8
      },
      {
        "name": "Large goat milk",
        "count": 4
      },
      {
        "name": "Golden egg",
        "count": 2
      },
      {
        "name": "Golden milk",
        "count": 2
      },
      {
        "name": "Large golden milk",
        "count": 2
      },
      {
        "name": "Wool",
        "count": 2
      }
    ]
  },
  "shippedSlugs": [
    "almond",
    "amaranth",
    "amber-pen-shell",
    "ancient-compass",
    "ancient-map",
    "ancient-rainbow-armband",
    "apple",
    "archer",
    "artichoke",
    "assam-silk-moth",
    "avocado",
    "bamboo-shoot",
    "banana",
    "barley",
    "barracuda",
    "basil",
    "batik-shawl",
    "beach-snow-globe",
    "beaded-necklace",
    "beet",
    "bell-pepper",
    "beryl",
    "black-sea-urchin",
    "black-truffle",
    "blackberry",
    "blood-clam",
    "blue-dahlia",
    "blue-mask",
    "blue-tang",
    "bluebell-blossom",
    "blueberry",
    "bok-choy",
    "brisingida-starfish",
    "broken-blade",
    "broken-sundial",
    "brontosaurus-hip",
    "bronze-hammer",
    "bronze-kelp",
    "bronze-statue",
    "cactus",
    "calico-scallop",
    "cannonball-jellyfish",
    "canola",
    "carrot",
    "carved-ring-holder",
    "cauliflower",
    "centipede",
    "chard",
    "cheese-wheel",
    "cherrystone-clam",
    "chipped-helmet",
    "chipped-pottery-jug",
    "chub",
    "clam-shell",
    "cockle",
    "cocoa-bean",
    "coconut",
    "coffee",
    "coffee-beans",
    "common-starfish",
    "coral-tall-coconut",
    "corn",
    "cosmo",
    "cotton",
    "cranberry",
    "crayfish",
    "cricket",
    "crystal-ball",
    "cucumber",
    "daffodil",
    "daisy",
    "diorite",
    "dragonfruit",
    "dragons-tears",
    "dragons-trisula",
    "duck-egg",
    "dumbphone",
    "durian",
    "earth-geode",
    "egg",
    "eggplant",
    "fairy-rose",
    "feather",
    "fire-agate",
    "fire-geode",
    "firefly",
    "flame-scallop",
    "flowerhat-jellyfish",
    "fly",
    "gallimimus-claw",
    "gallimimus-pelvis",
    "gallimimus-torso",
    "gardenia",
    "garlic",
    "gemstone-beads",
    "gemstone-candlestick",
    "gemstone-hourglass",
    "gesha-coffee-bean",
    "ginseng",
    "glass-bowl",
    "glass-star",
    "goat-cheese-wheel",
    "goat-milk",
    "gold-fish",
    "gold-kelp",
    "golden-bell",
    "golden-egg",
    "golden-keris",
    "golden-milk",
    "goldfish",
    "goldglow",
    "gooseneck-barnacle",
    "grape",
    "green-mask",
    "ground-beetle",
    "hammerstone",
    "harpoon",
    "helixpur-blossom",
    "hibiscus",
    "hot-pepper",
    "iris",
    "jackfruit",
    "jackknife-clam",
    "jade-locket",
    "jasmine-crown",
    "jepun",
    "juice",
    "junonia-shell",
    "labu",
    "large-duck-egg",
    "large-duck-mayonnaise",
    "large-egg",
    "large-feather",
    "large-gesha-coffee-bean",
    "large-goat-milk",
    "large-golden-egg",
    "large-golden-milk",
    "large-llama-wool",
    "large-milk",
    "large-quail-egg",
    "large-wool",
    "larkspur",
    "leather-parchment",
    "lemon",
    "lettuce",
    "lily",
    "little-wood-satyr-butterfly",
    "llama-wool",
    "lychee",
    "mackerel",
    "magic-lamp",
    "mammoth-claw",
    "mammoth-leg",
    "mammoth-tail",
    "mammoth-torso",
    "mango",
    "mangosteen",
    "maple-leafcutter-moth",
    "marble",
    "marinethorn-blossom",
    "marinip",
    "masquerade-mask",
    "mayonnaise",
    "melon",
    "milk",
    "moonlight-earrings",
    "mosasaurus-leg",
    "mosasaurus-tail",
    "mosasaurus-torso",
    "moth",
    "murex",
    "mystery-geode",
    "okra",
    "olive",
    "orange",
    "orchid",
    "osmium-kelp",
    "pacific-oyster",
    "papaya",
    "peach",
    "pear",
    "pearl-chain",
    "peas",
    "peony",
    "petalia",
    "pine-sphinx",
    "pineapple",
    "plesiosaurus-pelvis",
    "plesiosaurus-spine",
    "plesiosaurus-tail",
    "plesiosaurus-torso",
    "plum",
    "pom-pom-crab",
    "poppy",
    "potato",
    "praying-mantis",
    "prehistoric-bowl",
    "pterodactyl-arm",
    "pterodactyl-leg",
    "pterodactyl-tail",
    "pterodactyl-torso",
    "pumpkin",
    "purple-cowry-shell",
    "puss-moth",
    "quail-egg",
    "radish",
    "rambutan",
    "red-admiral",
    "red-cabbage",
    "red-reefbud",
    "rice",
    "rose",
    "royal-bowl",
    "ruby-red-dragonet",
    "rusty-anchor",
    "rusty-spear",
    "salmon",
    "salt-lamp",
    "sardines",
    "scarites-beetle",
    "sea-mushroom",
    "sea-salt",
    "sea-slug",
    "sea-spud",
    "seaweed",
    "shadow-puppet",
    "shallot",
    "shell-anklet",
    "shiitake",
    "ships-wheel",
    "shrimp",
    "silver-kelp",
    "silver-sandal",
    "silver-spoon",
    "skunk-cleaner-shrimp",
    "sky-disk",
    "small-figurine",
    "snail",
    "snake-fruit",
    "snow-globe",
    "snowdrop",
    "sockeye-salmon",
    "soldier-beetle",
    "soybean",
    "spring-sealeaf",
    "sproutfruit",
    "squid",
    "starfruit",
    "steamer-clam",
    "stegosaurus-claw",
    "stegosaurus-leg",
    "stegosaurus-spine",
    "stegosaurus-torso",
    "stingray-jewel-plate",
    "stone-hand-axe",
    "strawberry",
    "sugarcane",
    "sunflower",
    "sweet-potato",
    "taro-root",
    "tea-leaf",
    "tiger-swallowtail-butterfly",
    "tilapia",
    "tomato",
    "triceratops-arm",
    "triceratops-skull",
    "triceratops-torso",
    "tulip",
    "turnip",
    "twinshade-sealeaf",
    "tyrannosaurus-arm",
    "tyrannosaurus-claw",
    "tyrannosaurus-spine",
    "tyrannosaurus-torso",
    "underwater-tablet",
    "unfinished-clay-statue",
    "velociraptor-claw",
    "velociraptor-leg",
    "velociraptor-torso",
    "violet",
    "violin-beetle",
    "wasabi",
    "wasp",
    "watercress",
    "watermelon",
    "wheat",
    "whelk",
    "white-hibiscus",
    "white-truffle",
    "wood-carving",
    "wooden-hand-fan",
    "wool",
    "zebra-mussel"
  ]
}
